### PR TITLE
Test part2: Complete

### PR DESCRIPTION
**Pull request by Vgonma**
# Requirements

- [x] Test a function for editing the task description.
- [x] Test a function for updating an item's 'completed' status.
- [x] Test the "Clear all completed" function.

# Test descriptions

- Edit description: Tested changes in the local array and in localStorage.
- Update completed status: Tested changes in the local array and in localStorage.
- Clear all completed: Tested changes in the local array, localStorage and, DOM.

### CODE REVIEW

**Review by ha-manel — COMMENTED** [review]
# STATUS: INVALID 🔴 
Hi @Vgonma 
I'm sure you put a lot of effort into this project but this PR is invalid because this is a pair programming activity but you worked on it solo 😓 

Your partner needs to have some contribution to the project (commits) unless you have permission the work alone, in that case kindly add a screenshot to your PR description 👍 
Best of luck!

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Vgonma** [comment]
@ha-manel What do you mean I worked solo? There are commits of both of us.
image
This is the second time this has happened so we were very careful so that it would not happen again. I am not sure why you are saying that it was solo work. If there is something that is being done wrong please let me know so we can figure it out and not have this happen again.

**Comment by ha-manel** [comment]
@Vgonma It said 1 participant in your PR, and even the commits didn't have an icon or anything so I concluded that you worked solo 🤔 

Please submit the PR for review again, getting invalidated doesn't count as a review so you still have 3 reviews for this milestone 👍 

I apologize for the inconvenient, good luck to you both 💯

**Comment by Vgonma** [comment]
I just resubmitted it and it should be online. Thanks for the quick answer.

**Review by Felix45 — APPROVED** [review]
# Approved :green_circle: 
Hi @Vgonma  and @gjuliao 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights :heavy_check_mark: 
:heavy_check_mark:  Descriptive pull request title and summary :clap: 
:heavy_check_mark: Good descriptive commit messages :clap: 
:heavy_check_mark: All linter checks are setup and passing :clap: 
:heavy_check_mark: All unit tests are passing with green checks :clap: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
